 

spring.application.name=lms

spring.datasource.url=jdbc:mysql://powaka.h.filess.io:3306/lms_application_meantonto
spring.datasource.username=lms_application_meantonto
spring.datasource.password=4559fbdecbf15fa7e7ff3b4d9397939e33b2a569

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.database-platform=org.hibernate.dialect.MySQLDialect