spring.application.name=lms

spring.datasource.url=jdbc:mysql://shortline.proxy.rlwy.net:20650/lms
spring.datasource.username=root
spring.datasource.password=WWjxoWgWPKknTpBCHttOdEOvBaBhGZta

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect